version: '3'

services:
    netsus:
        container_name: netsus
        build:
            context: .
            dockerfile: dockerfile
        ports:
            - "8080:80"
            - "8443:443"